tae2089/coding_test_study

- 태빈/go/boj_1000.go
- 태빈/go/boj_1000_test.go
---
[백준 1000번 - A+B ](https://www.acmicpc.net/problem/1000)
- 수학 기초
```go
package coding
func PlusAandB(a,b int ) int{
return a + b
}
```
- 없음
- 없음
-  예제입니다.
> Taebin - 백준 1000번 문제 풀이

- 태빈/go/programers/programer_26.go
- 태빈/go/programers/programer_26_test.go
- 태빈/go/programers/programer_27.go
- 태빈/go/programers/programer_27_test.go
---
- [FindMbti](https://school.programmers.co.kr/learn/courses/30/lessons/118666)
- 구현
```go
func FindMbti(survey []string, choices []int) string {
mbtiType := map[string]int{
"R":0,
"T":0,
"C":0, 
"F":0,
"J":0,
"M":0,
"A":0,
"N":0,
}
for idx ,question := range survey{
switch choices[idx]{
case 1:
mbtiType[string(question[0])] +=3
case 2:
mbtiType[string(question[0])] +=2
case 3:
mbtiType[string(question[0])] +=1
case 5:
mbtiType[string(question[1])] +=1
case 6:
mbtiType[string(question[1])] +=2
case 7:
mbtiType[string(question[1])] +=3
}
}
firstChar := getMbti("R","T",mbtiType)
secondChar := getMbti("C","F",mbtiType)
thirdChar := getMbti("J","M",mbtiType)
fourthChar := getMbti("A","N",mbtiType)
return firstChar+secondChar+thirdChar+fourthChar
}
func getMbti(type1,type2 string, dict …
```
> [프로그래머스] 성격 유형 검사

- sangmin/vowel_dict.py
---
[모음 사전]
사전에 알파벳 모음 'A', 'E', 'I', 'O', 'U'만을 사용하여 만들 수 있는, 길이 5 이하의 모든 단어가 수록되어 있습니다. 사전에서 첫 번째 단어는 "A"이고, 그다음은 "AA"이며, 마지막 단어는 "UUUUU"입니다.
단어 하나 word가 매개변수로 주어질 때, 이 단어가 사전에서 몇 번째 단어인지 return 하도록 solution 함수를 완성해주세요.
https://school.programmers.co.kr/learn/courses/30/lessons/84512
from itertools import product (중복조합)
1) A, E, I, O, U의 1~5글자의 모든 조합의 수를 만든다. (이 때 중복은 제거)
2) 빈 리스트에 모든 조합의 수를 넣는다.
3) 리스트를 정렬하고 index+1를 return 한다.
```python
from itertools import product
def solution(word):
dict = []
for i in range(1, 6):
for v in product(['A','E','I','O','U'], repeat=i):
dict.append(''.join(list(v)))
dict.sort()
return dict.index(word) + 1
```
사전을 만들 때, 중복을 제거하는 법이 힘들었다. -> product 라이브러리를 사용해 중복조합 해결
-
-
-  문자열을 가지고 순서대로 리스트를 만드는 유형이 굉장히 많이 나오는데, itertools를 사용하면 더 쉽게 풀 수 있는 것 같다.
> [프로그래머스 - 모음 사전] 이상민

- README.md
- 예진/BOJ_9012.py
- 예진/PRO_92334.py
- [신고 결과 받기](https://school.programmers.co.kr/learn/courses/30/lessons/92334)
- ??
```python
def solution(id_list, report, k):
report = list(set(report)) # 신고 중복제거
reported_ct = {x : 0 for x in id_list} # 유저별 신고 당한 횟수
ans_dict = {x : 0 for x in id_list} # 유저별 받는 처리 결과 메일 수
for r in report: # 유저별 신고 당한 횟수 count
reported_ct[r.split()[1]] += 1
for r in report:
a, b = r.split()
if reported_ct[b] >= k: # 신고당한 횟수가 k보다 크면
ans_dict[a] += 1 # 유저별 수신 메일 수 +1
return list(ans_dict.values())
```
- (없음)
- (없음)
-  뭔가 더 간단한 방법이 있을 법도 한 문제 같습니다..
> [프로그래머스 - 신고결과받기] 문예진

- 태빈/go/programers/programer_28.go
- 태빈/go/programers/programer_28_test.go
---
- [2016년](https://school.programmers.co.kr/learn/courses/30/lessons/12901?language=go)
- 구현
- 금요일이 1월1일이기에 첫번째 값으로 두고 금토일월화수목 순으로 배열을 만든다.
- 1월부터~12월까지 윤년을 포함해서 배열을 생성한다.
- a개월 만큼 날을 더해준다.
- b에서 1을 빼서 날짜를 구해준다.
- 요일이 총 7이므로 이걸로 나머지를 구해서 요일을 구해준다.
```go
func GetDate(a,b int) string{
day := []string{"FRI", "SAT", "SUN", "MON", "TUE", "WED", "THU"}
month := []int{31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31}
date := 0
for i:=0 ; i<a-1 ;i ++{
date += month[i]
}
date += b-1;
return day[date%7]
}
```
- 달력 만드는 방법을 까먹어서 이 부분 찾아보는데 약간 걸렸습니다
- 없음
- 없음
> [PROGRAMMERS] 2016년

- YG/BOJ_19236_청소년상어.py
---
- [청소년상어](https://www.acmicpc.net/problem/19236)
- DFS
```python
dx = [0, -1, -1, -1, 0, 1, 1, 1]
dy = [-1, -1, 0, 1, 1, 1, 0, -1]
def move_fishes(fish, space, fish_list):
for i in fish_list:
y, x, direction = fish[i]
for j in range(8):
d = (direction + j) % 8
nx = x + dx[d]
ny = y + dy[d]
if 0 <= nx < 4 and 0 <= ny < 4 and space[ny][nx] != 17:
if space[ny][nx] != 0:
fish[i] = (ny, nx, d)
fish[space[ny][nx]] = (y, x, fish[space[ny][nx]][2])
space[y][x] = space[ny][nx]
space[ny][nx] = i
else:
fish[i] = (ny, nx, d)
space[ny][nx] = i
space[y][x] = 0
break
def shark(y, x, d, fish, space, fish_list):
ans_list = [0]
for i in range(1, 4):
nx = x + dx[d] * i
ny = y + dy[d] * i
if 0 <= nx < 4 and 0 <= ny < 4 and 0 < space[ny][nx] < 17:
f = …
```
> [BOJ-19236] 청소년상어

- 태빈/go/leetcode/lee_938.go
- 태빈/go/leetcode/lee_938_test.go
---
- [Range Sum of BST](https://leetcode.com/problems/range-sum-of-bst/)
- Binary Search Tree
```go
type TreeNode struct {
Val int
Left *TreeNode
Right *TreeNode
}
func rangeSumBST(root *TreeNode, low int, high int) int {
arr := make([]int,0)
var total int
isNodeInRange(root, low, high,&arr)
for _, value := range arr {
total += value
}
return total
}
func isNodeInRange(node *TreeNode, low, high int, arr *[]int){
if node == nil {
return
}
isNodeInRange(node.Left,low,high,arr)
if node.Val >=low && node.Val <=high {
*arr = append(*arr, node.Val)
}
isNodeInRange(node.Right,low,high,arr)
}
```
- dfs로 하기위해 재귀함수 구현을 하는데 오랜만에 해서 햇갈렸습니다. ㅎㅎ
- 없음
-  없음
> [LEETCODE] Range Sum of BST

- 예진/PRO_1845.py
- [폰켓몬](https://school.programmers.co.kr/learn/courses/30/lessons/1845)
- 해시
- 폰켓몬 종류가 몇 개 들어있는지만 알면 해결되는 거라고 생각했습니당,,
```python
def solution(nums):
if len(set(nums)) <= len(nums) / 2:
return len(set(nums))
else:
return len(nums) / 2
```
- (없음)
- Lv1. 이긴 하지만
- 혹시 '해시'로 어떻게 푸는지 아시는 분..?
-  (없음)
> [PRO-1845] 폰켓몬

- YSB/[BOJ-13305]주유소.PY
---
- https://www.acmicpc.net/problem/13305
- 그리디
```python
n = int(input())
len_street = list(map(int,input().split()))
fee = list(map(int,input().split()))
minfee = fee[0]
sum = 0
for i in range(n-1):
if minfee > fee[i]:
minfee = fee[i]
sum += minfee * len_street[i]
print(sum)
```
- 
- 
-
> [BOJ-13305] 주유소

- CHN/BOJ_10804_카드역배치.py
---
- https://www.acmicpc.net/problem/10804
- 정렬
```python
a = list(range(21))
for _ in range(10) :
start, fin = map(int, input().split())
for i in range((fin-start+1)//2):
a[start+i], a[fin-i] = a[fin-i], a[start+i]
a.pop(0)  
for x in a:
print(x, end = ' ')
```
- swap이라는 개념을 새로 알게 되었습니다
-
-
> BOJ_10804_카드역배치.py

- YG/BOJ_19237_어른상어.py
---
- [어른상어](https://www.acmicpc.net/problem/19237)
- 구현
```python
dx = [0, 0, -1, 1]
dy = [-1, 1, 0, 0]
def smell_shark(visited, shark_location, k):
for shark, (i, j, _) in shark_location.items():
visited[i][j] = (shark, k)
def time_count(visited, n):
for i in range(n):
for j in range(n):
t = visited[i][j]
if t: # not empty space
if t[1]-1 > 0:
visited[i][j] = (t[0], t[1]-1)
else:
visited[i][j] = 0
def move_shark(space, visited, shark_location, shark_priority, n):
moved_location = defaultdict(lambda: list())
for shark, (y, x, d) in shark_location.items():
cnt = 0
for t in range(4):
direction = shark_priority[(shark, d)][t]
nx = x + dx[direction]
ny = y + dy[direction]
if 0 <= nx < n and 0 <= ny < n …
```
> [BOJ-19237] 어른상어

- 태빈/go/leetcode/lee_100.go
- 태빈/go/leetcode/lee_100_test.go
---
- [Same Tree](https://leetcode.com/problems/same-tree/)
- Binary Tree
```go
func isSameTree(p *TreeNode, q *TreeNode) bool {
//둘다 nil인지 체크 
if p == nil || q == nil {
return p == q
}
// 두개의 값이 동일한지
if p.Val != q.Val {
return false
}
// 재귀를 통한 다음 노드들의 값 체크
return isSameTree(p.Left, q.Left) && isSameTree(p.Right, q.Right)
}
```
- 없음
- 없음
-
> [LEETCODE-100] Same Tree

- 태빈/go/leetcode/lee2236_test.go
- 태빈/go/leetcode/lee_100.go
- 태빈/go/leetcode/lee_100_test.go
- 태빈/go/leetcode/lee_2236.go
---
- [Root Equals Sum of Children](https://leetcode.com/problems/root-equals-sum-of-children)
- Binary Tree
```go
type TreeNode struct {
Val int
Left *TreeNode
Right *TreeNode
}
func checkTree(root *TreeNode) bool {
leftNode, rightNode := root.Left, root.Right
sum := leftNode.Val + rightNode.Val
return root.Val == sum
}
```
- 없음
- 없음
-
> [LEECODE-2236] Root Equals Sum of Children

- YSB/77487_헤비유저가소유한장소.sql
---
헤비 유저가 소유한 장소
-https://school.programmers.co.kr/learn/courses/30/lessons/77487
- ?
```sql
select b.*
from places as b
where b.host_id in 
(select a.host_id
from (select host_id, count(*) as cnt 
from places 
group by host_id) as a
where a.cnt >=2)
order by id
```
- 
- 서브쿼리를 쓰는 방법 밖에 없는지 궁금합니다. 
-
> [PRO_77487]헤비 유저가 소유한 장소

- PRO_42579.py
- [베스트 앨범](https://school.programmers.co.kr/learn/courses/30/lessons/42579)
- 해시
```python
def solution(genres, plays):
total = {x: 0 for x in set(genres)}
for i in range(len(genres)):
total[genres[i]] += plays[i] # 장르별 재생 횟수 합
g_total = {}
for i, (g, p) in enumerate(zip(genres, plays)):
if g not in g_total:
g_total[g] = [(i, p)]
else:
g_total[g].append((i, p)) # 장르별 재생 횟수 list
ans = []
for (k, v) in sorted(total.items(), key = lambda x: x[1], reverse = True): # 재생횟수 높은 장르에서
for (i, p) in sorted(g_total[k], key = lambda x: x[1], reverse = True)[:2]: # 베스트 재생 2개씩
ans.append(i) # 정답에 추가
return ans
```
- 마지막 베스트 재생 2개씩 인덱스 가져오는걸 어떻게 하면 좋을지 아이디어가 생각이 잘 안났습니다..
- 괜히 꼬아서 생각하다가 하루 온종일 걸렸네여!ㅠ
- (없음)
-  (없음)
> [PRO-42579] 베스트 앨범

- 태빈/go/programers/programer_29.go
- 태빈/go/programers/programer_29_test.go
---
- [문자열 내 마음대로 정렬하기](https://school.programmers.co.kr/learn/courses/30/lessons/12915)
- 문자열
```go
func RandomSorting(strings []string , n int)[] string{
sort.Slice(strings, func(i, j int) bool {
if strings[i][n] == strings[j][n] {
return strings[i] < strings[j]
}
return strings[i][n] < strings[j][n]
})
return strings
}
```
- 같은 문자는 어떻게 정렬할지에 대해서 고민못했던게 어려웠습니다.
예시로 abc, abb를 비교할때를 고려하지 못했는데 질문하기 보다가 
이 부분을 고려해야 하는걸 알 수 있었습니다.
- 없음
- 없음
> [PROGRAMMERS] 문자열 내 마음대로 정렬하기

- YG/BOJ_20056_마법사상어와파이어볼.py
---
- [마법사 상어와 파이어볼](https://www.acmicpc.net/problem/20056)
- 구현
```python
dx = [0, 1, 1, 1, 0, -1, -1, -1]
dy = [-1, -1, 0, 1, 1, 1, 0, -1]
def check(direction):
if direction[0] in [0, 2, 4, 6]: # even number
for d in direction:
if d in [1, 3, 5, 7]: # odd number
return [1, 3, 5, 7]
else: # odd number
for d in direction:
if d in [0, 2, 4, 6]: # even number
return [1, 3, 5, 7]
return [0, 2, 4, 6]
def move_fireball(matrix_to_fireball, fireball_dict, n):
tmp_matrix_to_fireball = defaultdict(lambda: list()) # this dictionary includes that which fireball is in each (row, column)
for k, v in matrix_to_fireball.items():
for v_ in v:
mass, velocity, direction = fireball_dict[v_]
ny = k[0] + dy[direction] * …
```
> [BOJ-20056] 마법사상어와파이어볼

- 태빈/go/leetcode/lee_11.go
- 태빈/go/leetcode/lee_11_test.go
---
- [Container With Most Water](https://leetcode.com/problems/container-with-most-water/)
- 그리디 알고리즘
```go
func maxArea(height []int) int {
startPoint := 0
endPoint := len(height) - 1
maxArea := 0
for startPoint < endPoint {
area := minPoints(height[startPoint], height[endPoint]) * (endPoint - startPoint)
if area > maxArea {
maxArea = area
}
if height[startPoint] < height[endPoint] {
startPoint++
}else{
endPoint--
}
}
return maxArea
}
func minPoints(startPoint, endPoint int) int {
if startPoint < endPoint {
return startPoint
}
return endPoint
}
```
- 없음
- 없음
- 올리고 싶어서 올려요~
> [LEETCODE-11] Container With Most Water

- YG/BOJ_20057_마법사상어와토네이도.py
---
- [마법사 상어와 토네이도](https://www.acmicpc.net/problem/20057)
- 구현
```python
dx = [-1, 0, 1, 0]
dy = [0, 1, 0, -1]
def sand_move(x, y, amount, array, direction, ans, n):
total = 0
target = int(amount * 0.01)
for i in [1, 3]:
nx = x + dx[(direction + i) % 4]
ny = y + dy[(direction + i) % 4]
if 0 <= nx < n and 0 <= ny < n: # move (inside sand)
array[ny][nx] += target
else: # remove (outside sand)
ans += target
total += target
target = int(amount * 0.07)
for i in [1, 3]:
nx = x + dx[direction] + dx[(direction + i) % 4]
ny = y + dy[direction] + dy[(direction + i) % 4]
if 0 <= nx < n and 0 <= ny < n: # move (inside sand)
array[ny][nx] += target
else: # remove (outside sand)
ans += target
total += target
target = int(amount * 0.02)
for i in …
```
> [BOJ-20057] 마법사상어와토네이도

- 태빈/go/programers/programer_30.go
- 태빈/go/programers/programer_30_test.go
---
[체육복](https://school.programmers.co.kr/learn/courses/30/lessons/42862)
- 그리디 알고리즘
```go
package coding
func RentCloth(n int, lost []int, reserve []int) int {
student := [32]int{0,}
var result int
for _,v := range reserve{
student[v] +=1
}
for _,v := range lost{
student[v] -=1
}
for i:= 1; i<=n; i++{
if student[i] == -1{
if student[i - 1] == 1{
student[i - 1] = 0
student[i] = 0
}else if student[i +1 ] == 1{
student[i + 1] = 0
student[i] = 0
}
}
}
for i:=1;i<=n;i++{
if student[i] != -1{
result++
}
}
return  result
}
```
- 체육복을 2개 갖고 있는 학생이 체육복 하나를 도둑맞을 때를 고려해서 풀어야 합니다.
- 없음
-  없음
> [PROGRAMMERS] 체육복

- [BOJ-1541]잃어버린괄호.py
---
- https://www.acmicpc.net/problem/1065
- 함수
```python
a = int(input())
def func(x):
n = str(x)
dif = int(n[1]) - int(n[0])
for i in range(len(n)-1):
if int(n[i+1])-int(n[i]) != dif:
return 0
return 1
ans = 9
if a <10:
print(a)
else:
for j in range(10,a+1):
ans += func(j)
print(ans)
```
- 
-
-
> [BOJ-1065]한수

- LEET_125.py
- https://leetcode.com/problems/valid-palindrome/
- ?
```python
import re
class Solution:
def isPalindrome(self, s: str) -> bool:
s = re.sub(r'[^a-z|0-9]| ', "", s.lower())
if len(s)%2 != 0: rev = list(s[len(s)//2+1:])
else: rev = list(s[len(s)//2:])
rev.reverse()
rev = "".join(rev)
return s[:len(s)//2] == rev
```
- (없음)
- (없음)
-  정규표현식의 맛을 봐버렸ㅇ...
> [LEET-125] Valid Palindrome

- 태빈/go/leetcode/lee_91.go
- 태빈/go/leetcode/lee_91_test.go
---
- [Decode Ways](https://leetcode.com/problems/decode-ways/)
- Dynamic Programing
```go
func numDecodings(s string) int {
dp := make([]int, len(s))
if s[0] == '0' {
return 0
}
dp[0] = 1
for i := 1; i < len(s); i++ {
curOneSum := int(s[i] - '0')
curTenSum := int(s[i-1]-'0')*10 + curOneSum
if curOneSum != 0 {
dp[i] += dp[i-1]
}
if curTenSum >= 10 && curTenSum <= 26 {
if i >= 2 {
dp[i] += dp[i-2]
} else {
dp[i] += 1
}
}
}
return dp[len(s)-1]
}
```
- 숫자 자릿수를 주위해야하는데 이부분이 이해가 안가 오래걸렸습니다.
- 없음
-  없음
> [LEECODE-91] Decode Ways

- CHN/HACK_Binary_Tree.sql
---
- https://www.hackerrank.com/challenges/binary-search-tree-1/problem?isFullScreen=true
- 
```sql
select N, 
CASE 
when N = any (select N from BST where P is NULL) then "Root"
when N = any( select P from BST) then "Inner"
else "Leaf"
END 
from BST order by N; 
```
-처음에 문제 보며 살짝 띠용했던 것 같습니다 ㅎㅎ
-
-
> [HACK] Binary_Tree.sql

- 예진/PRO_42748.py
- [K번째수](https://school.programmers.co.kr/learn/courses/30/lessons/42748)
- 정렬
```python
def solution(array, commands):
return [sorted(array[c[0]-1 : c[1]])[c[2]-1] for c in commands]
```
- (없음)
- (없음)
- deque 문제 고르려다가 문제 선택 실패..🤦🏻‍♀️
> [PRO-42748] K번째 수

- 태빈/go/leetcode/lee_112.go
- 태빈/go/leetcode/lee_112_test.go
---
- [Path Sum](https://leetcode.com/problems/path-sum/)
- DFS
```go
package leetcode
func hasPathSum(root *TreeNode, targetSum int) bool {
if root == nil {
return false
}
if targetSum == 0 && root.Left == nil && root.Right == nil {
return true
}
return hasPathSum(root.Left, targetSum-root.Val) && hasPathSum(root.Right, targetSum-root.Val)
}
```
- 없음
- 없음
-  약간씩 DFS에 대해 이해가 가기 시작했습니다:)
> [LEECODE-112] Path Sum

- YSB/[BOJ-18258]큐2.py
---
- https://www.acmicpc.net/problem/18258
- 큐
```python
from collections import deque
import sys
data = deque()
n = int(sys.stdin.readline())
def push(x):
data.append(x)
def pop():
if len(data) == 0:
print(-1)
else:
res = data.popleft()
print(res)
def size():
print(len(data))
def empty():
if len(data) == 0:
print(1)
else:
print(0)
def front():
if len(data) == 0:
print(-1)
else:
print(data[0])
def back():
if len(data) == 0:
print(-1)
else:
print(data[-1])
for _ in range(n):
ord = sys.stdin.readline().split()
if ord[0] == 'pop':
pop()
elif ord[0] == 'size':
size()
elif ord[0] =='empty':
empty()
elif ord[0] == 'front':
front()
elif ord[0] == 'back':
back()
else:
push(ord[1])
```
-  시간초과 
-
-
> [BOJ-18258]큐2

- YG/BOJ_1655_가운데를말해요.py
- YG/BOJ_2617_구슬찾기.py
---
- [구슬 찾기](https://www.acmicpc.net/problem/2617)
- DFS
```python
import sys
def dfs(dic, visited, start_point):
result = 1
for i in dic[start_point]:
if not visited[i]:
visited[i] = True
result += dfs(dic, visited, i)
return result
if __name__ == '__main__':
n, m = map(int, input().split())
heavy_dict = defaultdict(lambda: list())
light_dict = defaultdict(lambda: list())
for _ in range(m):
heavy, light = map(int, input().split())
heavy_dict[light-1].append(heavy-1)
light_dict[heavy-1].append(light-1)
ans = 0
for i in range(n):
visited = [False] * n
visited[i] = True
result = dfs(heavy_dict, visited, i) - 1
if result >= (n+1)//2:
ans += 1
continue
visited = [False] * n
visited[i] = True
result = dfs(light_dict, visited, i) - …
```
> [BOJ-2617] 구슬 찾기

- YG/BOJ_1655_가운데를말해요.py
- YG/BOJ_2617_구슬찾기.py
---
- [가운데를 말해요](https://www.acmicpc.net/problem/1655)
- 힙
```python
import heapq
import sys
if __name__ == '__main__':
n = int(input())
min_heap = []
max_heap = []
for i in range(n):
target_num = int(input())
if i == 0:
heapq.heappush(min_heap, -target_num)
print(target_num)
else:
if (i + 1) % 2 == 0:
heapq.heappush(max_heap, target_num)
else:
heapq.heappush(min_heap, -target_num)
num1 = -heapq.heappop(min_heap)
num2 = heapq.heappop(max_heap)
if num1 < num2:
heapq.heappush(min_heap, -num1)
heapq.heappush(max_heap, num2)
else:
heapq.heappush(min_heap, -num2)
heapq.heappush(max_heap, num1)
print(-min_heap[0])
```
- 처음에는 힙으로 접근할 생각을 못해서, binary search로 접근했다가 시간초과가 나왔었네용
- 이후에는 우선순위큐로 접근해봤는데, 우선순위큐는 put과 get으로만 …
> [BOJ-1655] 가운데를 말해요

- 태빈/go/leetcode/lee_16.go
- 태빈/go/leetcode/lee_16_test.go
---
- [3Sum Closest](https://leetcode.com/problems/3sum-closest)
- two pointer
```go
func threeSumClosest(nums []int, target int) int {
sort.Ints(nums)
var answer int = 0
var minDiff int = math.MaxInt32
length := len(nums)
for i := 0; i < length; i++ {
l, h := i+1, length-1
for l < h {
s := nums[i] + nums[l] + nums[h]
if abs(target-s) < minDiff {
minDiff = abs(target - s)
answer = s
}
if s > target {
h--
} else {
l++
}
}
}
return answer
}
func abs(x int) int {
if x < 0 {
return -x
}
return x
}
```
- 없음
- 없음
-  없음
> [LEETCODE-16] 3Sum Closest

- YG/BOJ_21939_문제추천시스템Version1.py
---
- [문제 추천 시스템 Version 1](https://www.acmicpc.net/problem/21939)
- heap
```python
import heapq
import sys
n = int(input())
min_q = []
max_q = []
problem_list = defaultdict(lambda: 0)
for _ in range(n):
p, l = map(int, input().split())
heapq.heappush(min_q, (l, p))
heapq.heappush(max_q, (-l, -p))
problem_list[p].add(l)
removed_list = defaultdict(lambda: set())
m = int(input())
for _ in range(m):
command = input().split()
if command[0] == 'recommend':
if int(command[1]) == 1:
while True:
if -max_q[0][0] in removed_list[-max_q[0][1]]:
heapq.heappop(max_q)
else:
break
print(-max_q[0][1])
else:
while True:
if min_q[0][0] in removed_list[min_q[0][1]]:
heapq.heappop(min_q) …
```
> [BOJ-21939] 문제 추천 시스템 Version1

- YSB/BOJ-11659]구간합구하기4.py
---
- https://www.acmicpc.net/problem/11659
- 누적합
```python
import sys
n,m = map(int,input().split())
num_list = list(map(int,input().split()))
sum_list = [0]
temp = 0
for i in num_list:
temp += i
sum_list.append(temp)
for i in range(m):
a,b = map(int,input().split())
print(sum_list[b]-sum_list[a-1])
```
- 처음에 그냥 sum으로 풀었는데 시간초과가 나서 미리 sum_list를 생성해야 했습니다. 
-
-
> [BOJ-11659]구간합구하기4

- 태빈/go/leetcode/lee_ 334.go
- 태빈/go/leetcode/lee_ 334_test.go
---
- [Increasing Triplet Subsequence](https://leetcode.com/problems/increasing-triplet-subsequence)
- greedy
```go
import "math"
func increasingTriplet(nums []int) bool {
length := len(nums)
if length < 3 {
return false
}
first := nums[0]
second := math.MaxInt32
for i := 1; i < length; i++ {
num := nums[i]
if num > second {
return true
} else if num > first {
second = num
} else {
first = num
}
}
return false
}
```
- 없음 
- 없음
-  없음
> [LEECODE-334]  Increasing Triplet Subsequence

- 태빈/go/leetcode/lee_237.go
---
- [Delete Node in a Linked List] (https://leetcode.com/problems/delete-node-in-a-linked-list)
- linked list
```go
type ListNode struct {
Val  int
Next *ListNode
}
func deleteNode(node *ListNode) {
node.Val, node.Next = node.Next.Val, node.Next.Next
}
```
- 없음
- 없음
-  없음
> [LEETCODE-237] Delete Node in a Linked List

- YG/BOJ_3078_좋은친구.py
---
- [좋은 친구](https://www.acmicpc.net/problem/3078)
- 큐
```python
import sys
from queue import deque
if __name__ == '__main__':
n, k = map(int, input().strip().split())
q = deque()
candidate = defaultdict(lambda: 0)
ans = 0
for i in range(n):
curr = len(input().strip())
if len(q) == k:
ans += candidate[curr]
tmp = q.popleft()
candidate[tmp] -= 1
q.append(curr)
candidate[curr] += 1
else:
ans += candidate[curr]
q.append(curr)
candidate[curr] += 1
print(ans)
```
- 없음
- 없음
-  큐를 사용해야 하는데, 바로 다음 것이 아니라 일정 윈도우 내의 것을 봐야 하는 상황이면 이렇게 dict 를 이용하면 편하네용
> [BOJ-3078] 좋은 친구

- 태빈/go/programers/programer_31.go
- 태빈/go/programers/programer_31_test.go
---
- [로또의 최고 순위와 최저 순위](https://school.programmers.co.kr/learn/courses/30/lessons/77484)
- 구현
```go
package coding
func Lotto(lottos []int, win_nums []int) []int {
// key - 맞은 갯수 , value - 순위
lottoRank := map[int]int{
6:1,
5:2,
4:3,
3:4,
2:5,
1:6,
0:6,
}
lottoDic := make(map[int]int)
zeroCnt := 0
result := 0
for _, num := range lottos {
if(num == 0){
zeroCnt++
continue
}
lottoDic[num] = 1
}
for _, num := range win_nums {
lottoDic[num] += 1
if(lottoDic[num] == 2){
result+=1
}
}
min := lottoRank[result]
max := lottoRank[result+zeroCnt]
return []int{max,min}
}
```
- 없음
- 없음
-  로또 당첨자의 최고 순위와 최저 순위를 파악하는 문제입니다
> [PROGRAMMERS] 로또의 최고 순위와 최저 순위
